force-app/main/default/components/SelectionDayWashUpComponent.component, force-app/main/default/components/SelectionDayWashUpComponent.component-meta.xml
=> [DevOps Center] Merge WI-000115 to SIT

force-app/main/default/flows/Position_IA_Informed_of_Tentative_Match.flow-meta.xml
=> [DevOps Center] Merge WI-000116 to SIT

force-app/main/default/classes/QualifiedToTeachToTextTest.cls, force-app/main/default/classes/QualifiedToTeachToTextTest.cls-meta.xml, force-app/main/default/objects/Associate_Record__c/fields/May_Additionally_Teach_Text__c.field-meta.xml, force-app/main/default/objects/Associate_Record__c/fields/Qualified_to_Teach_Text__c.field-meta.xml, force-app/main/default/objects/Associate_Record__c/fields/Test_Text_Field__c.field-meta.xml, force-app/main/default/triggers/QualifiedToTeachToText.trigger, force-app/main/default/triggers/QualifiedToTeachToText.trigger-meta.xml
=> [DevOps Center] Merge WI-000118 to SIT

force-app/main/default/classes/QualifiedToTeachToTextTest.cls, force-app/main/default/classes/QualifiedToTeachToTextTest.cls-meta.xml, force-app/main/default/flows/Position_IA_Informed_of_Tentative_Match.flow-meta.xml, force-app/main/default/objects/Associate_Record__c/fields/May_Additionally_Teach_Text__c.field-meta.xml, force-app/main/default/objects/Associate_Record__c/fields/Qualified_to_Teach_Text__c.field-meta.xml, force-app/main/default/objects/Associate_Record__c/fields/Test_Text_Field__c.field-meta.xml, force-app/main/default/triggers/QualifiedToTeachToText.trigger, force-app/main/default/triggers/QualifiedToTeachToText.trigger-meta.xml
=> [DevOps Center] Merge SIT to Staging

force-app/main/default/groups/IA_VIC_Allocation_Alerts.group-meta.xml, force-app/main/default/triggers/MayAdditionallyTeachToText.trigger
=> [DevOps Center] Merge WI-000122 to SIT

force-app/main/default/objects/Lead/fields/Last_Activity_Date_Range__c.field-meta.xml
=> [DevOps Center] Merge WI-000126 to SIT

force-app/main/default/duplicateRules/npe5__Affiliation__c.Block_Duplicate_Affiliation_Creation.duplicateRule-meta.xml, force-app/main/default/matchingRules/npe5__Affiliation__c.matchingRule-meta.xml
=> [DevOps Center] Merge WI-000134 to SIT

force-app/main/default/objects/Account/Account.object-meta.xml, force-app/main/default/objects/Account/fields/Cluster_Hub__c.field-meta.xml, force-app/main/default/objects/Account/fields/Cluster__c.field-meta.xml, force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
=> [DevOps Center] Merge WI-000146 to SIT

force-app/main/default/flows/Populate_Unique_Key_On_Affiliation_Record.flow-meta.xml, force-app/main/default/matchingRules/npe5__Affiliation__c.matchingRule-meta.xml, force-app/main/default/objects/npe5__Affiliation__c/fields/Compound_Key__c.field-meta.xml, force-app/main/default/objects/npe5__Affiliation__c/npe5__Affiliation__c.object-meta.xml
=> [DevOps Center] Merge WI-000148 to SIT

force-app/main/default/layouts/Account-University.layout-meta.xml, force-app/main/default/layouts/Contact-General Contacts.layout-meta.xml, force-app/main/default/quickActions/Engage_University.quickAction-meta.xml
=> [DevOps Center] Merge WI-000153 to SIT

force-app/main/default/dashboards/LDP/LDP_Incoming_Associate/Recruitment_Team_Dashboards/tfLJATTTZvJfYcdvGLBwfowlYMTyqo.dashboard-meta.xml, force-app/main/default/dashboards/Recruitment/EtwMyEOaHgMAegFOMNHTAZLOBnVfny.dashboard-meta.xml
=> [DevOps Center] Merge WI-000154 to SIT

force-app/main/default/duplicateRules/npe5__Affiliation__c.Block_Duplicate_Affiliation_Creation.duplicateRule-meta.xml, force-app/main/default/flows/Affiliation_Update_Status_Based_On_End_Date.flow-meta.xml, force-app/main/default/flows/Populate_Unique_Key_On_Affiliation_Record.flow-meta.xml
=> [DevOps Center] Merge WI-000149 to SIT

force-app/main/default/quickActions/Engage_University.quickAction-meta.xml
=> [DevOps Center] Merge WI-000168 to SIT

force-app/main/default/flexipages/Application_Record_Page.flexipage-meta.xml, force-app/main/default/flows/Application_Nurturing_Process_Scheduler_Part_A.flow-meta.xml, force-app/main/default/flows/Application_Nurturing_Process_Scheduler_Part_B.flow-meta.xml, force-app/main/default/flows/Application_Opened_Email_Application_Nurturing.flow-meta.xml, force-app/main/default/layouts/Application__c-Application Layout.layout-meta.xml, force-app/main/default/objects/Application__c/Application__c.object-meta.xml, force-app/main/default/objects/Application__c/fields/Application_Withdrawn__c.field-meta.xml, force-app/main/default/objects/Application__c/fields/Last_Application_Nurturing_Activity__c.field-meta.xml, force-app/main/default/objects/Application__c/fields/Unit__c.field-meta.xml
=> [DevOps Center] Merge WI-000203 to SIT

force-app/main/default/flows/Send_Application_Workshop_SMS_Application_Nurturing.flow-meta.xml
=> [DevOps Center] Merge WI-000205 to SIT

force-app/main/default/flows/Send_Book_a_Call_with_your_RM_SMS_Application_Nurturing.flow-meta.xml, force-app/main/default/objects/User/User.object-meta.xml, force-app/main/default/objects/User/fields/RM_Applicant_Booking_URL__c.field-meta.xml
=> [DevOps Center] Merge WI-000208 to SIT

force-app/main/default/flows/Application_Nurturing_Process_Scheduler_Part_A.flow-meta.xml, force-app/main/default/flows/Application_Nurturing_Process_Scheduler_Part_B.flow-meta.xml, force-app/main/default/flows/Send_Book_a_Call_with_your_RM_SMS_Application_Nurturing.flow-meta.xml, force-app/main/default/flows/Send_Reminder_to_Submit_SMS_Application_Nurturing.flow-meta.xml, force-app/main/default/objects/Application__c/fields/Last_Application_Nurturing_Activity__c.field-meta.xml
=> [DevOps Center] Merge WI-000219 to SIT

force-app/main/default/flows/Application_Reviewed_Reminder_Closed_Application_Nurturing.flow-meta.xml, force-app/main/default/flows/Create_Reminder_to_Review_Application_Application_Nurturing.flow-meta.xml
=> [DevOps Center] Merge WI-000184 to SIT

force-app/main/default/flows/Confirm_Commitment_Call_Activity_logged_before_closing_reminders_Application_Nur.flow-meta.xml
=> [DevOps Center] Merge WI-000222 to SIT

force-app/main/default/flows/Update_Approved_by_RM_for_Application_Application_Nurturing.flow-meta.xml
=> [DevOps Center] Merge WI-000223 to SIT

force-app/main/default/classes/ApplicationLeadFormController_Test.cls, force-app/main/default/classes/ApplicationLeadFormController_Test.cls-meta.xml, force-app/main/default/classes/ContactAffiliationUpdationBatchable.cls, force-app/main/default/classes/ContactAffiliationUpdationBatchable.cls-meta.xml, force-app/main/default/classes/ContactAffiliationUpdationBatchable_Test.cls, force-app/main/default/classes/ContactAffiliationUpdationBatchable_Test.cls-meta.xml, force-app/main/default/classes/SendEmailController_Test.cls
=> [DevOps Center] Merge WI-000229 to SIT

force-app/main/default/classes/ContactAffiliationUpdationBatchable.cls
=> [DevOps Center] Merge WI-000231 to SIT

force-app/main/default/flexipages/Contact_Lightning_Page_Layout.flexipage-meta.xml, force-app/main/default/objects/Contact/recordTypes/General.recordType-meta.xml
=> [DevOps Center] Merge WI-000232 to SIT

force-app/main/default/flows/FLP_Contact_Create_Alumni_Affiliation.flow-meta.xml, force-app/main/default/flows/FLP_Contact_Create_Fellow_Affiliation.flow-meta.xml, force-app/main/default/flows/LDP_Contact_Create_Alumni_Affiliation.flow-meta.xml, force-app/main/default/flows/LDP_Contact_Create_Associate_Affiliation.flow-meta.xml
=> [DevOps Center] Merge WI-000233 to SIT

force-app/main/default/flows/Application_Nurturing_Process_Scheduler_Part_A.flow-meta.xml
=> [DevOps Center] Merge WI-000234 to SIT

force-app/main/default/flows/Application_Nurturing_Process_Scheduler_Part_A.flow-meta.xml, force-app/main/default/flows/Set_Last_Application_Nurturing_Activity_field_on_new_Application.flow-meta.xml
=> [DevOps Center] Merge WI-000235 to SIT

force-app/main/default/flows/FLP_Contact_Create_Alumni_Affiliation.flow-meta.xml, force-app/main/default/flows/FLP_Contact_Create_Fellow_Affiliation.flow-meta.xml, force-app/main/default/flows/LDP_Contact_Create_Alumni_Affiliation.flow-meta.xml, force-app/main/default/flows/LDP_Contact_Create_Associate_Affiliation.flow-meta.xml
=> [DevOps Center] Merge WI-000236 to SIT

force-app/main/default/flows/Affiliation_Update_Status_Based_On_End_Date.flow-meta.xml
=> [DevOps Center] Merge WI-000237 to SIT

force-app/main/default/flows/Create_Commitment_Call_Activity_Screenflow_Application_Nurturing.flow-meta.xml, force-app/main/default/flows/Create_Initial_Call_Activity_Screenflow_Application_Nurturing.flow-meta.xml, force-app/main/default/flows/Create_Reminder_to_conduct_Commitment_Call_Application_Nurturing.flow-meta.xml, force-app/main/default/flows/Create_Reminder_to_conduct_Initial_Call_Application_Nurturing.flow-meta.xml, force-app/main/default/flows/Create_Reminder_to_conduct_Second_Call_Application_Nurturing.flow-meta.xml
=> [DevOps Center] Merge WI-000240 to SIT

force-app/main/default/flows/Final_Follow_Up_Email_Application_Nurturing.flow-meta.xml
=> [DevOps Center] Merge WI-000242 to SIT

force-app/main/default/flows/FLP_Contact_Create_Applicant_Affiliation.flow-meta.xml
=> [DevOps Center] Merge WI-000243 to SIT

force-app/main/default/lwc/sendEmail/sendEmail.html, force-app/main/default/lwc/sendEmail/sendEmail.js
=> [DevOps Center] Merge WI-000246 to SIT

force-app/main/default/flows/Complete_Your_Application_Email_Application_Nurturing.flow-meta.xml, force-app/main/default/flows/LDP_Contact_Create_Alumni_Affiliation.flow-meta.xml, force-app/main/default/flows/Sending_SMS_to_Contact.flow-meta.xml
=> [DevOps Center] Merge WI-000247 to SIT

force-app/main/default/flows/FLP_Contact_Create_Alumni_Affiliation.flow-meta.xml, force-app/main/default/flows/LDP_Contact_Create_Alumni_Affiliation.flow-meta.xml
=> [DevOps Center] Merge WI-000248 to SIT

force-app/main/default/flows/Affiliation_Update_Status_Based_On_End_Date.flow-meta.xml, force-app/main/default/flows/FLP_Contact_Create_Alumni_Affiliation.flow-meta.xml, force-app/main/default/flows/Populate_Unique_Key_On_Affiliation_Record.flow-meta.xml
=> [DevOps Center] Merge WI-000250 to SIT

force-app/main/default/classes/ContactAffiliationUpdationBatchable.cls, force-app/main/default/flexipages/Affiliation_Lightning_Page_Layout.flexipage-meta.xml, force-app/main/default/layouts/npe5__Affiliation__c-Affiliation Layout.layout-meta.xml, force-app/main/default/objects/npe5__Affiliation__c/fields/TTL_Application__c.field-meta.xml, force-app/main/default/objects/npe5__Affiliation__c/validationRules/Start_Date_Required.validationRule-meta.xml
=> [DevOps Center] Merge WI-000251 to SIT

force-app/main/default/classes/SendEmailController.cls
=> [DevOps Center] Merge WI-000252 to SIT

force-app/main/default/classes/ContactAffiliationUpdationBatchable.cls, force-app/main/default/classes/ContactAffiliationUpdationBatchable_Test.cls
=> [DevOps Center] Merge WI-000254 to SIT

force-app/main/default/flexipages/Contact_ASSOCIATE_Lightning_Layout.flexipage-meta.xml, force-app/main/default/flows/FLP_Contact_Create_Fellow_Affiliation.flow-meta.xml, force-app/main/default/flows/Update_RM_Email_Signature_on_Application_Owner_update.flow-meta.xml, force-app/main/default/objects/Contact/fields/RM_Email_Signature__c.field-meta.xml, force-app/main/default/objects/User/fields/Email_Signature__c.field-meta.xml, force-app/main/default/objects/User/fields/Pronouns__c.field-meta.xml
=> [DevOps Center] Merge WI-000257 to SIT

force-app/main/default/flows/Populate_Unique_Key_On_Affiliation_Record.flow-meta.xml
=> [DevOps Center] Merge WI-000258 to SIT

force-app/main/default/flows/Application_Nurturing_Process_Scheduler_Part_A.flow-meta.xml
=> [DevOps Center] Merge WI-000259 to SIT

force-app/main/default/classes/ContactAffiliationUpdationBatchable.cls
=> [DevOps Center] Merge WI-000262 to SIT

force-app/main/default/classes/SendEmailController.cls, force-app/main/default/lwc/sendCampaignEmail/sendCampaignEmail.html, force-app/main/default/lwc/sendCampaignEmail/sendCampaignEmail.js
=> [DevOps Center] Merge WI-000264 to SIT
